"use client";
import { useState } from "react";
import { MorphIcon } from "morphicons/react";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
const paths={arrow:"M5 12H19M12 5L19 12L12 19",diagonal:"M5 19L19 5M5 5H19V19",menu:"M4 8H20M4 16H20",close:"M6 6L18 18M6 18L18 6",plus:"M4 12H20M12 4V20",minus:"M4 12H20",smile:"M3 12C3 24 21 24 21 12M7 5V7M17 5V7"};
function Icon({name="diagonal",size=24}:{name?:keyof typeof paths;size?:number}){return <MorphIcon icon={paths[name]} size={size} strokeWidth={1.5} reducedMotion="user"/>}
function CTA({light=false}:{light?:boolean}){const [hover,setHover]=useState(false);return <a className={`cta ${light?"light":""}`} href="#contacts" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)}>Записаться на приём<span><Icon name={hover?"arrow":"diagonal"}/></span></a>}
const services=["Лечение зубов","Имплантация","Протезирование","Профессиональная гигиена","Ортодонтия","Эстетика улыбки","Хирургия","Косметологическая стоматология"];
const descriptions=["Восстанавливаем здоровье зубов. На приёме врач проведёт осмотр и предложит план лечения.","Восстанавливаем утраченные зубы. Возможность имплантации определяет врач после диагностики.","Подбираем конструкции для восстановления функции и внешнего вида зубов.","Помогаем поддерживать здоровье зубов и дёсен. Объём процедуры определяем на осмотре.","Занимаемся исправлением прикуса. Подходящий метод подбирает врач-ортодонт.","Обсудим реставрацию зубов и ваши пожелания к улыбке на консультации.","Хирургический приём и индивидуальный план дальнейшего восстановления.","Обсудим доступные процедуры и показания на приёме у специалиста."];
export default function Home(){const [menu,setMenu]=useState(false);const [service,setService]=useState("");const [faq,setFaq]=useState("");return <main>
<div className="topline"><span>СТОМАТОЛОГИЯ В КОПЕЙСКЕ</span><span>ул. Калинина, 16　 /　 Пн–пт 9:00–19:00 · Сб–вс 10:00–16:00</span></div>
<header><a className="logo" href="#" aria-label="Ева Дент — главная">ева<span>✳</span>дент<small>СТОМАТОЛОГИЯ С ЗАБОТОЙ</small></a><nav aria-label="Основная навигация"><a href="#services">Услуги</a><a href="#about">О клинике</a><a href="#team">Врачи</a><a href="#contacts">Контакты</a></nav><a className="header-phone" href="tel:+79120825115">+7 (912) 08-25-115</a><button className="menu-button" aria-label={menu?"Закрыть меню":"Открыть меню"} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}><Icon name={menu?"close":"menu"}/></button></header>
{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Мобильная навигация">{[["services","Услуги"],["about","О клинике"],["team","Врачи"],["contacts","Контакты"]].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<Icon/></a>)}</nav>}
<section className="hero"><div className="hero-copy"><div className="eyebrow"><b>✳</b> МЕСТО, ГДЕ ВАШЕЙ УЛЫБКЕ РАДЫ</div><h1>Улыбайтесь.<br/>Вам <em>идёт.</em></h1><div className="hero-bottom"><p>Бережная стоматология<br/>для вас и вашей семьи.<br/>Внимательно. Понятно. С заботой.</p><CTA/></div><div className="hero-index"><span>ВАША УЛЫБКА — НАША ОБЩАЯ ИСТОРИЯ</span><span>01 / 05</span></div></div><div className="hero-photo"><img src="/images/doctor.png" alt="Улыбки на фотографии с сайта Ева Дент" fetchPriority="high"/><span className="photo-label">БОЛЬШЕ ПОВОДОВ УЛЫБАТЬСЯ</span><a className="round-link" href="#about"><Icon name="smile" size={42}/><span>Давайте<br/>знакомиться</span><Icon/></a></div></section>
<div className="principles"><span>Честный подход</span><b>✳</b><span>Забота о каждом</span><b>✳</b><span>Всё для вашей улыбки</span><b>✳</b><span>Ева Дент</span></div>
<section id="services" className="section"><div className="section-heading"><span className="eyebrow">01 / ЧЕМ МЫ ПОМОЖЕМ</span><h2>От заботы о зубах —<br/>до <em>новой улыбки.</em></h2><p>Выслушаем, объясним и подберём<br/>решение именно для вас.</p></div><Accordion type="single" collapsible className="service-grid" value={service} onValueChange={setService}>{services.map((title,i)=><AccordionItem className={`service-card service-${i}`} value={String(i)} key={title}><AccordionTrigger className="service-trigger"><span className="service-number">0{i+1}</span><span className="service-title">{title}</span><span className="service-icon"><Icon name={service===String(i)?"minus":"plus"}/></span></AccordionTrigger><AccordionContent className="service-details"><p>{descriptions[i]}</p><a href="#contacts">Обсудить с врачом ↗</a></AccordionContent></AccordionItem>)}</Accordion></section>
<section id="about" className="about"><div className="about-title"><span className="eyebrow">02 / БЛИЖЕ К ВАМ</span><h2>Хорошая<br/>стоматология.<br/><em>По-человечески.</em></h2><p>Мы хотим, чтобы в кресле стоматолога вы чувствовали себя спокойно. Поэтому начинаем со знакомства и разговора.</p><CTA light/></div><div className="about-image"><img src="/images/clinic.jpg" alt="Стоматологический кабинет клиники Ева Дент" loading="lazy"/><span>КОПЕЙСК, КАЛИНИНА, 16</span></div><div className="about-note"><span className="huge-star">✳</span><p>Сначала — понять.<br/>Потом — лечить.</p><span>Объясним каждый шаг и ответим<br/>на вопросы до начала лечения.</span></div><div className="about-facts"><div><span>01</span><h3>Внимание к деталям</h3><p>Сертифицированные материалы и комплексный подход к лечению.</p></div><div><span>02</span><h3>Забота в одном месте</h3><p>От профилактики до восстановления зубов — в знакомой клинике.</p></div></div></section>
<section id="team" className="section"><div className="section-heading"><span className="eyebrow">03 / ЛЮДИ, КОТОРЫМ ДОВЕРЯЮТ</span><h2>За каждой улыбкой —<br/><em>свой человек.</em></h2><a className="text-link" href="https://evadent74.ru/sertifikaty/" target="_blank" rel="noreferrer">Образование и сертификаты <Icon/></a></div><div className="team-grid">{[["ЕЛ","Леготина","Евгения Леонидовна","Главный врач · стоматолог-терапевт, хирург, ортопед"],["АШ","Шмидт","Андрей Эдуардович","Зубной врач"],["АГ","Горелова","Алёна Владимировна","Стоматолог-ортодонт"]].map(([initial,surname,name,role],i)=><article className="doctor" key={surname}><div className={`doctor-monogram monogram-${i}`}><span>{initial}</span><small>ЕВА ДЕНТ / КОМАНДА</small></div><h3>{surname}<br/>{name}</h3><p>{role}</p><a href="#contacts">Записаться к врачу <Icon/></a></article>)}</div></section>
<section className="faq section"><div><span className="eyebrow">04 / БЕЗ ЛИШНИХ ВОЛНЕНИЙ</span><h2>Давайте<br/><em>разберёмся.</em></h2></div><Accordion type="single" collapsible value={faq} onValueChange={setFaq}>{[["Как записаться на первый приём?","Позвоните нам по номеру +7 (912) 08-25-115. Администратор поможет выбрать специалиста и удобное время."],["Где посмотреть стоимость лечения?","Прайс опубликован на действующем сайте клиники. Итоговый план и стоимость уточняются после осмотра."],["Можно ли прийти, если я боюсь лечить зубы?","Расскажите о своих переживаниях при записи и на приёме. Врач объяснит, что предстоит сделать, и обсудит с вами ход лечения."],["Где находится клиника?","Копейск, улица Калинина, дом 16, помещение 4. Работаем по будням с 9:00 до 19:00, в выходные с 10:00 до 16:00."]].map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger className="faq-trigger">{q}<span><Icon name={faq===String(i)?"minus":"plus"}/></span></AccordionTrigger><AccordionContent className="faq-answer">{a}{i===1&&<a className="text-link" target="_blank" rel="noreferrer" href="https://evadent74.ru/">Перейти на сайт клиники ↗</a>}</AccordionContent></AccordionItem>)}</Accordion></section>
<section id="contacts" className="contacts"><span className="eyebrow">05 / НАЧНЁМ С ЗНАКОМСТВА</span><div className="contact-heading"><h2>Ваша улыбка.<br/><em>Наша забота.</em></h2><a className="call-circle" href="tel:+79120825115"><Icon size={38}/><span>Позвонить<br/>и записаться</span></a></div><div className="contact-grid"><div><small>ЖДЁМ ВАС</small><a href="https://yandex.ru/maps/?text=Копейск%20Калинина%2016%20Ева%20Дент" target="_blank" rel="noreferrer">Копейск,<br/>ул. Калинина, 16 ↗</a><p>Помещение 4</p></div><div><small>ПОЗВОНИТЕ ИЛИ НАПИШИТЕ</small><a href="tel:+79120825115">+7 (912) 08-25-115</a><a className="email" href="mailto:eva_dent@mail.ru">eva_dent@mail.ru</a></div><div><small>ВРЕМЯ ДЛЯ ВАС</small><p>Пн–пт · 9:00–19:00<br/>Сб–вс · 10:00–16:00</p></div></div></section>
<footer><a className="logo" href="#">ева<span>✳</span>дент</a><p>ООО «Ева Дент»<br/>ИНН 7430029981 · ОГРН 1187456012094</p><a href="https://evadent74.ru/" target="_blank" rel="noreferrer">Документы клиники ↗</a><span>© {new Date().getFullYear()} Ева Дент</span></footer><p className="medical-note">Имеются противопоказания. Необходима консультация специалиста.</p>
</main>}
